include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: ubuntu:bionic

test:
  extends:
    - .julia:1.3
  script:
    # - ls .julia/artifacts
    - julia -e 'using Pkg; Pkg.add("FFTW")'
    - ls .julia/artifacts
